# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20140518003221) do

  create_table "alunos", :force => true do |t|
    t.string  "nu_inscricao"
    t.integer "nu_ano"
    t.string  "tp_escola"
    t.string  "in_tp_ensino"
    t.string  "pk_cod_entidade"
    t.string  "cod_municipio_esc"
    t.string  "no_municipio_esc"
    t.string  "uf_esc"
    t.string  "id_dependencia_adm"
    t.string  "sit_func"
    t.string  "in_presenca_cn"
    t.string  "in_presenca_ch"
    t.string  "in_presenca_lc"
    t.string  "in_presenca_mt"
    t.float   "nu_nt_cn"
    t.float   "nu_nt_ch"
    t.float   "nu_nt_lc"
    t.float   "nu_nt_mt"
    t.string  "tx_respostas_cn"
    t.string  "tx_respostas_ch"
    t.string  "tx_respostas_lc"
    t.string  "tx_respostas_mt"
    t.string  "id_prova_cn"
    t.string  "id_prova_ch"
    t.string  "id_prova_lc"
    t.string  "id_prova_mt"
    t.string  "tp_lingua"
    t.string  "ds_gabarito_cn"
    t.string  "ds_gabarito_ch"
    t.string  "ds_gabarito_lc"
    t.string  "ds_gabarito_mt"
    t.string  "in_status_redacao"
    t.float   "nu_nota_comp1"
    t.float   "nu_nota_comp2"
    t.float   "nu_nota_comp3"
    t.float   "nu_nota_comp4"
    t.float   "nu_nota_comp5"
    t.float   "nu_nota_redacao"
  end

  create_table "application", :id => false, :force => true do |t|
    t.string "nu_inscricao"
    t.string "nu_ano"
    t.string "idade"
    t.string "tp_sexo"
    t.string "cod_municipio_insc"
    t.string "no_municipio_insc"
    t.string "uf_insc"
    t.string "st_conclusao"
    t.string "ano_concluiu"
    t.string "tp_escola"
    t.string "in_tp_ensino"
    t.string "tp_estado_civil"
    t.string "tp_cor_raca"
    t.string "in_unidade_hospitalar"
    t.string "in_baixa_visao"
    t.string "in_cegueira"
    t.string "in_surdez"
    t.string "in_deficiencia_auditiva"
    t.string "in_surdo_cegueira"
    t.string "in_deficiencia_fisica"
    t.string "in_deficiencia_mental"
    t.string "in_deficit_atencao"
    t.string "in_dislexia"
    t.string "in_gestante"
    t.string "in_lactante"
    t.string "in_idoso"
    t.string "in_autismo"
    t.string "in_sabatista"
    t.string "in_braille"
    t.string "in_ampliada"
    t.string "in_ledor"
    t.string "in_acesso"
    t.string "in_transcricao"
    t.string "in_libras"
    t.string "in_leitura_labial"
    t.string "in_mesa_cadeira_rodas"
    t.string "in_mesa_cadeira_separada"
    t.string "in_apoio_perna"
    t.string "in_guia_interprete"
    t.string "in_certificado"
    t.string "no_entidade_certificacao"
    t.string "uf_entidade_certificacao"
    t.string "pk_cod_entidade"
    t.string "cod_municipio_esc"
    t.string "no_municipio_esc"
    t.string "uf_esc"
    t.string "id_dependencia_adm"
    t.string "id_localizacao"
    t.string "sit_func"
    t.string "cod_municipio_prova"
    t.string "no_municipio_prova"
    t.string "uf_municipio_prova"
    t.string "in_presenca_cn"
    t.string "in_presenca_ch"
    t.string "in_presenca_lc"
    t.string "in_presenca_mt"
    t.string "nu_nt_cn"
    t.string "nu_nt_ch"
    t.string "nu_nt_lc"
    t.string "nu_nt_mt"
    t.string "tx_respostas_cn"
    t.string "tx_respostas_ch"
    t.string "tx_respostas_lc"
    t.string "tx_respostas_mt"
    t.string "id_prova_cn"
    t.string "id_prova_ch"
    t.string "id_prova_lc"
    t.string "id_prova_mt"
    t.string "tp_lingua"
    t.string "ds_gabarito_cn"
    t.string "ds_gabarito_ch"
    t.string "ds_gabarito_lc"
    t.string "ds_gabarito_mt"
    t.string "in_status_redacao"
    t.string "nu_nota_comp1"
    t.string "nu_nota_comp2"
    t.string "nu_nota_comp3"
    t.string "nu_nota_comp4"
    t.string "nu_nota_comp5"
    t.string "nu_nota_redacao"
  end

  create_table "escola_id", :id => false, :force => true do |t|
    t.string "pk_cod_entidade"
    t.float  "nu_nt_cn"
    t.float  "nu_nt_ch"
    t.float  "nu_nt_lc"
    t.float  "nu_nt_mt"
    t.float  "nu_nota_redacao"
  end

  create_table "escolas", :force => true do |t|
    t.string "pk_cod_entidade"
    t.string "cidade"
    t.string "estado"
    t.string "endereco"
    t.string "telefone"
    t.string "email"
    t.float  "presen_cien_nat_2012"
    t.float  "presen_cien_hum_2012"
    t.float  "presen_lingua_cod_2012"
    t.float  "presen_matematica_2012"
    t.float  "presen_redacao_2012"
    t.float  "presen_cien_nat_2011"
    t.float  "presen_cien_hum_2011"
    t.float  "presen_lingua_cod_2011"
    t.float  "presen_matematica_2011"
    t.float  "presen_redacao_2011"
    t.float  "media_cien_nat_2012"
    t.float  "media_cien_hum_2012"
    t.float  "media_lingua_cod_2012"
    t.float  "media_matematica_2012"
    t.float  "media_redacao_2012"
    t.float  "media_cien_nat_2011"
    t.float  "media_cien_hum_2011"
    t.float  "media_lingua_cod_2011"
    t.float  "media_matematica_2011"
    t.float  "media_redacao_2011"
    t.string "nome"
    t.string "rede"
    t.string "regiao"
    t.string "nr_endereco"
    t.string "complemento_endereco"
    t.string "bairro"
    t.string "cep"
    t.string "ddd"
    t.string "situacao_funcionamento"
  end

  add_index "escolas", ["cidade"], :name => "index_escolas_on_cidade"
  add_index "escolas", ["estado"], :name => "index_escolas_on_estado"
  add_index "escolas", ["nome"], :name => "index_escolas_on_nome"
  add_index "escolas", ["pk_cod_entidade"], :name => "index_escolas_on_pk_cod_entidade"

  create_table "escolas_total", :id => false, :force => true do |t|
    t.text "ano_censo"
    t.text "pk_cod_entidade"
    t.text "nome_escola"
    t.text "rede"
    t.text "id_dependencia_adm"
    t.text "dependencia_administrativa"
    t.text "catescprivada"
    t.text "localizacao"
    t.text "regiao"
    t.text "fk_cod_estado"
    t.text "uf"
    t.text "municipio"
    t.text "cod_municipio"
    t.text "pk_cod_municipio_old"
    t.text "no_distrito"
    t.text "endereco"
    t.text "nr_endereco"
    t.text "complemento_endereco"
    t.text "bairro"
    t.text "cep"
    t.text "ddd"
    t.text "telefone"
    t.text "telefone_publico_1"
    t.text "fax"
    t.text "correio_eletronico"
    t.text "situacao_funcionamento"
    t.text "id_latitude"
    t.text "id_longitude"
    t.text "dt_ano_letivo_inicio"
    t.text "dt_ano_letivo_termino"
    t.text "finslucrativos"
    t.text "mant_emp"
    t.text "mant_sind"
    t.text "mant_sist_s"
    t.text "mant_ong"
    t.text "mant_s_fins"
    t.text "mod_ativ_complementar"
    t.text "orgciclos"
    t.text "func_predio_escolar"
    t.text "func_salas_empresa"
    t.text "func_prisional"
    t.text "func_templo_igreja"
    t.text "func_casa_professor"
    t.text "func_galpao"
    t.text "func_outros"
    t.text "func_salas_outra_esc"
    t.text "num_cnpj_escola_privada"
    t.text "num_cnpj_unidade_executora"
    t.text "documento_regulamentacao"
    t.text "conveniada_pp"
    t.text "tipo_convenio_poder_publico"
    t.text "locdiferenciada"
    t.text "acessibilidade"
    t.text "dependencias_pne"
    t.text "sanitario_pne"
    t.text "aee"
    t.text "sala_diretoria"
    t.text "sala_professor"
    t.text "secretaria"
    t.text "refeitorio"
    t.text "despensa"
    t.text "almoxarifado"
    t.text "auditorio"
    t.text "laboratorio_informatica"
    t.text "laboratorio_ciencias"
    t.text "sala_atendimento_especial"
    t.text "quadra_esportes_coberta"
    t.text "quadra_esportes_descoberta"
    t.text "patio_coberto"
    t.text "patio_descoberto"
    t.text "parque_infantil"
    t.text "cozinha"
    t.text "biblioteca"
    t.text "bercario"
    t.text "sanitario_dentro_predio"
    t.text "sanitario_fora_predio"
    t.text "sanitario_ei"
    t.text "banheiro_chuveiro"
    t.text "lavanderia"
    t.text "dependencias_outras"
    t.text "num_salas_existentes"
    t.text "num_salas_utilizadas"
    t.text "sala_leitura"
    t.text "alojam_aluno"
    t.text "alojam_professor"
    t.text "area_verde"
    t.text "num_funcionarios"
    t.text "alimentacao"
    t.text "agua_filtrada"
    t.text "agua_rede_publica"
    t.text "agua_poco_artesiano"
    t.text "agua_cacimba"
    t.text "agua_fonte_rio"
    t.text "agua_inexistente"
    t.text "energia_rede_publica"
    t.text "energia_gerador"
    t.text "energia_outros"
    t.text "energia_inexistente"
    t.text "esgoto_rede_publica"
    t.text "esgoto_fossa"
    t.text "esgoto_inexistente"
    t.text "lixo_coleta_periodica"
    t.text "lixo_queima"
    t.text "lixo_joga_outra_area"
    t.text "lixo_recicla"
    t.text "lixo_enterra"
    t.text "lixo_outros"
    t.text "internet"
    t.text "banda_larga"
    t.text "computadores"
    t.text "num_computadores"
    t.text "compusoalunos"
    t.text "num_comp_administrativos"
    t.text "equip_dvd"
    t.text "equip_impressora"
    t.text "equip_som"
    t.text "equip_multimidia"
    t.text "equip_fax"
    t.text "equip_foto"
    t.text "equip_parabolica"
    t.text "equip_copiadora"
    t.text "equip_retro"
    t.text "equip_tv"
    t.text "equip_videocassete"
    t.text "material_esp_nao_utiliza"
    t.text "material_esp_quilombola"
    t.text "material_esp_indigena"
    t.text "educacao_indigena"
    t.text "lingua_indigena"
    t.text "lingua_portuguesa"
    t.text "espaco_turma_pba"
    t.text "abre_final_semana"
    t.text "mod_ens_regular"
    t.text "mod_educ_especial"
    t.text "mod_eja"
    t.text "nescedbasica"
    t.text "mattotal"
    t.text "nesceir"
    t.text "matei"
    t.text "nesccrecher"
    t.text "matcreche"
    t.text "nescpprer"
    t.text "matpre"
    t.text "nescefr"
    t.text "matef"
    t.text "matefi"
    t.text "matef1"
    t.text "matef2"
    t.text "matef3"
    t.text "matef4"
    t.text "matef5"
    t.text "matef6"
    t.text "matef7"
    t.text "matef8"
    t.text "nescef14air"
    t.text "matef14ai"
    t.text "nescef58afr"
    t.text "matef58af"
    t.text "nescefs"
    t.text "mats"
    t.text "mat1s"
    t.text "mat2s"
    t.text "mat3s"
    t.text "mat4s"
    t.text "mat5s"
    t.text "mat6s"
    t.text "mat7s"
    t.text "mat8s"
    t.text "nescefa"
    t.text "mata"
    t.text "mat1a"
    t.text "mat2a"
    t.text "mat3a"
    t.text "mat4a"
    t.text "mat5a"
    t.text "mat6a"
    t.text "mat7a"
    t.text "mat8a"
    t.text "mat9a"
    t.text "nescemr"
    t.text "matem"
    t.text "matem1"
    t.text "matem2"
    t.text "matem3"
    t.text "matem4"
    t.text "matemns"
    t.text "nescemem"
    t.text "matem_em"
    t.text "matem1_em"
    t.text "matem2_em"
    t.text "matem3_em"
    t.text "matem4_em"
    t.text "matemns_em"
    t.text "nescemi"
    t.text "matem_i"
    t.text "matem1_i"
    t.text "matem2_i"
    t.text "matem3_i"
    t.text "matem4_i"
    t.text "matemns_i"
    t.text "nescemn"
    t.text "matem_n"
    t.text "matem1_n"
    t.text "matem2_n"
    t.text "matem3_n"
    t.text "matem4_n"
    t.text "nescepr"
    t.text "matep"
    t.text "nescepconc"
    t.text "matepconc"
    t.text "nescepsubseq"
    t.text "matepsubseq"
    t.text "nescejar"
    t.text "mateja"
    t.text "nescejaef"
    t.text "matejaef"
    t.text "nescejaem"
    t.text "matejaem"
    t.text "nescejapr"
    t.text "matejap"
    t.text "nescejapef"
    t.text "matejapef"
    t.text "matejap14"
    t.text "matejap58"
    t.text "matejappj"
    t.text "nescejapem"
    t.text "matejapem"
    t.text "nescejaspr"
    t.text "matejasp"
    t.text "nescejaspef"
    t.text "matejaspef"
    t.text "matejasp14"
    t.text "matejasp58"
    t.text "nescejaspem"
    t.text "matejaspem"
    t.text "nescejaepefr"
    t.text "matejaepef"
    t.text "nescejaepnmr"
    t.text "matejaepnm"
    t.text "nescejaspepefr"
    t.text "matejaspepef"
    t.text "nescejaspepnmr"
    t.text "matejaspepnm"
    t.text "nesceeincl"
    t.text "mateeincl"
    t.text "nescee"
    t.text "matesptot"
    t.text "nescedesp"
    t.text "matesp"
    t.text "nescedespexclus"
    t.text "matespexclus"
    t.text "nescedespclesp"
    t.text "matespclesp"
    t.text "escaces"
  end

  add_index "escolas_total", ["pk_cod_entidade"], :name => "index_escolas_total_on_pk_cod_entidade"

  create_table "eventos", :force => true do |t|
    t.integer  "escola_id"
    t.string   "tipo"
    t.integer  "ano"
    t.datetime "created_at",  :null => false
    t.datetime "updated_at",  :null => false
    t.integer  "tipo_indice"
  end

  add_index "eventos", ["escola_id"], :name => "index_eventos_on_escola_id"
  add_index "eventos", ["tipo"], :name => "index_eventos_on_tipo"

end
