# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20140517142905) do

  create_table "alunos", :force => true do |t|
    t.string  "nu_inscricao"
    t.integer "nu_ano"
    t.string  "tp_escola"
    t.string  "in_tp_ensino"
    t.string  "pk_cod_entidade"
    t.string  "cod_municipio_esc"
    t.string  "no_municipio_esc"
    t.string  "uf_esc"
    t.string  "id_dependencia_adm"
    t.string  "sit_func"
    t.string  "in_presenca_cn"
    t.string  "in_presenca_ch"
    t.string  "in_presenca_lc"
    t.string  "in_presenca_mt"
    t.float   "nu_nt_cn"
    t.float   "nu_nt_ch"
    t.float   "nu_nt_lc"
    t.float   "nu_nt_mt"
    t.string  "tx_respostas_cn"
    t.string  "tx_respostas_ch"
    t.string  "tx_respostas_lc"
    t.string  "tx_respostas_mt"
    t.string  "id_prova_cn"
    t.string  "id_prova_ch"
    t.string  "id_prova_lc"
    t.string  "id_prova_mt"
    t.string  "tp_lingua"
    t.string  "ds_gabarito_cn"
    t.string  "ds_gabarito_ch"
    t.string  "ds_gabarito_lc"
    t.string  "ds_gabarito_mt"
    t.string  "in_status_redacao"
    t.float   "nu_nota_comp1"
    t.float   "nu_nota_comp2"
    t.float   "nu_nota_comp3"
    t.float   "nu_nota_comp4"
    t.float   "nu_nota_comp5"
    t.float   "nu_nota_redacao"
  end

  create_table "application", :id => false, :force => true do |t|
    t.string "nu_inscricao"
    t.string "nu_ano"
    t.string "idade"
    t.string "tp_sexo"
    t.string "cod_municipio_insc"
    t.string "no_municipio_insc"
    t.string "uf_insc"
    t.string "st_conclusao"
    t.string "ano_concluiu"
    t.string "tp_escola"
    t.string "in_tp_ensino"
    t.string "tp_estado_civil"
    t.string "tp_cor_raca"
    t.string "in_unidade_hospitalar"
    t.string "in_baixa_visao"
    t.string "in_cegueira"
    t.string "in_surdez"
    t.string "in_deficiencia_auditiva"
    t.string "in_surdo_cegueira"
    t.string "in_deficiencia_fisica"
    t.string "in_deficiencia_mental"
    t.string "in_deficit_atencao"
    t.string "in_dislexia"
    t.string "in_gestante"
    t.string "in_lactante"
    t.string "in_idoso"
    t.string "in_autismo"
    t.string "in_sabatista"
    t.string "in_braille"
    t.string "in_ampliada"
    t.string "in_ledor"
    t.string "in_acesso"
    t.string "in_transcricao"
    t.string "in_libras"
    t.string "in_leitura_labial"
    t.string "in_mesa_cadeira_rodas"
    t.string "in_mesa_cadeira_separada"
    t.string "in_apoio_perna"
    t.string "in_guia_interprete"
    t.string "in_certificado"
    t.string "no_entidade_certificacao"
    t.string "uf_entidade_certificacao"
    t.string "pk_cod_entidade"
    t.string "cod_municipio_esc"
    t.string "no_municipio_esc"
    t.string "uf_esc"
    t.string "id_dependencia_adm"
    t.string "id_localizacao"
    t.string "sit_func"
    t.string "cod_municipio_prova"
    t.string "no_municipio_prova"
    t.string "uf_municipio_prova"
    t.string "in_presenca_cn"
    t.string "in_presenca_ch"
    t.string "in_presenca_lc"
    t.string "in_presenca_mt"
    t.string "nu_nt_cn"
    t.string "nu_nt_ch"
    t.string "nu_nt_lc"
    t.string "nu_nt_mt"
    t.string "tx_respostas_cn"
    t.string "tx_respostas_ch"
    t.string "tx_respostas_lc"
    t.string "tx_respostas_mt"
    t.string "id_prova_cn"
    t.string "id_prova_ch"
    t.string "id_prova_lc"
    t.string "id_prova_mt"
    t.string "tp_lingua"
    t.string "ds_gabarito_cn"
    t.string "ds_gabarito_ch"
    t.string "ds_gabarito_lc"
    t.string "ds_gabarito_mt"
    t.string "in_status_redacao"
    t.string "nu_nota_comp1"
    t.string "nu_nota_comp2"
    t.string "nu_nota_comp3"
    t.string "nu_nota_comp4"
    t.string "nu_nota_comp5"
    t.string "nu_nota_redacao"
  end

end
