class CreateAlunos < ActiveRecord::Migration
  def change
  create_table "alunos", :force => true do |t|
    t.string  "nu_inscricao"
    t.integer "nu_ano"
    t.string  "tp_escola"
    t.string  "in_tp_ensino"
    t.string  "pk_cod_entidade"
    t.string  "cod_municipio_esc"
    t.string  "no_municipio_esc"
    t.string  "uf_esc"
    t.string  "id_dependencia_adm"
    t.string  "sit_func"
    t.string  "in_presenca_cn"
    t.string  "in_presenca_ch"
    t.string  "in_presenca_lc"
    t.string  "in_presenca_mt"
    t.float   "nu_nt_cn"
    t.float   "nu_nt_ch"
    t.float   "nu_nt_lc"
    t.float   "nu_nt_mt"
    t.string  "tx_respostas_cn"
    t.string  "tx_respostas_ch"
    t.string  "tx_respostas_lc"
    t.string  "tx_respostas_mt"
    t.string  "id_prova_cn"
    t.string  "id_prova_ch"
    t.string  "id_prova_lc"
    t.string  "id_prova_mt"
    t.string  "tp_lingua"
    t.string  "ds_gabarito_cn"
    t.string  "ds_gabarito_ch"
    t.string  "ds_gabarito_lc"
    t.string  "ds_gabarito_mt"
    t.string  "in_status_redacao"
    t.float   "nu_nota_comp1"
    t.float   "nu_nota_comp2"
    t.float   "nu_nota_comp3"
    t.float   "nu_nota_comp4"
    t.float   "nu_nota_comp5"
    t.float   "nu_nota_redacao"
  end
  end
end
